<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Master Timetable Report</title>
    <style>
        @page {
            margin: 1cm;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.2;
        }

        /* Header Section */
        .report-header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
        }
        .main-title {
            font-size: 24px;
            font-weight: bold;
            color: #111;
            text-transform: uppercase;
            margin: 0;
        }
        .sub-title {
            font-size: 12px;
            color: #555;
            margin-top: 5px;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
            table-layout: fixed; /* Ensures fixed column widths */
        }
        th, td {
            border: 1px solid #999;
            padding: 5px;
            text-align: center;
            vertical-align: middle;
            word-wrap: break-word;
        }
        th {
            background-color: #eee;
            color: #000;
            font-weight: bold;
            font-size: 9px;
            text-transform: uppercase;
            height: 30px;
        }

        /* Specific Column Styles */
        .teacher-col {
            width: 12%; /* Teacher name column width */
            text-align: left;
            background-color: #fcfcfc;
            font-weight: bold;
            color: #000;
            font-size: 9px;
        }

        /* Cell Content */
        .class-badge {
            display: block;
            font-weight: bold;
            color: #006400; /* Dark Green */
            font-size: 10px;
        }
        .subject-text {
            display: block;
            color: #00008B; /* Dark Blue */
            font-size: 9px;
            margin-top: 2px;
        }
        .time-badge {
            display: block;
            color: #666;
            font-size: 7px;
            margin-top: 2px;
            font-style: italic;
        }

        /* Page Breaks */
        .page-break {
            page-break-after: always;
        }

        /* Footer */
        .footer {
            position: fixed;
            bottom: 0px;
            left: 0px;
            right: 0px;
            height: 20px;
            font-size: 8px;
            text-align: center;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
    </style>
</head>
<body>

    <div class="footer">
        Generated by School Timetable System on {{ date('Y-m-d H:i') }}
    </div>

    @foreach($days as $key => $dayName)
        @php $dayIndex = $key + 1; @endphp

        <div class="report-header">
            <h1 class="main-title">{{ $dayName }} Schedule</h1>
            <div class="sub-title">Master Timetable Overview &bull; Academic Year {{ date('Y') }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th class="teacher-col">Teacher</th>
                    @for($p = 1; $p <= $maxPeriod; $p++)
                        <th>P-{{ $p }}</th>
                    @endfor
                </tr>
            </thead>
            <tbody>
                @foreach($teachers as $teacher)
                    <tr>
                        <td class="teacher-col">
                            {{ $teacher->name }}
                            <div style="font-weight:normal; font-size:8px; color:#555;">{{ $teacher->short_code }}</div>
                        </td>

                        @for($p = 1; $p <= $maxPeriod; $p++)
                            @php
                                $entry = $masterTable[$teacher->id][$dayIndex][$p] ?? null;

                                // Time Calculation
                                $timeInfo = $periodTimings[$p] ?? null;
                                $startTime = $timeInfo ? \Carbon\Carbon::parse($timeInfo->start_time)->format('h:i') : '';
                                $endTime = $timeInfo ? \Carbon\Carbon::parse($timeInfo->end_time)->format('h:i') : '';
                                $timeString = ($startTime && $endTime) ? "$startTime-$endTime" : '';
                            @endphp

                            <td>
                                @if($entry)
                                    <span class="class-badge">{{ $entry->section->grade }}-{{ $entry->section->class_name }}</span>
                                    <span class="subject-text">{{ $entry->subject->name }}</span>

                                    @if($timeString)
                                        <span class="time-badge">{{ $timeString }}</span>
                                    @endif
                                @else
                                    <span style="color:#eee;">-</span>
                                @endif
                            </td>
                        @endfor
                    </tr>
                @endforeach
            </tbody>
        </table>

        @if(!$loop->last)
            <div class="page-break"></div>
        @endif

    @endforeach

</body>
</html>
